# Generated by Django 3.0.2 on 2020-02-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'AboutMe',
                'verbose_name_plural': 'AboutMes',
            },
        ),
        migrations.CreateModel(
            name='Beforeskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'beforeskills',
                'verbose_name_plural': 'beforeskillss',
            },
        ),
        migrations.CreateModel(
            name='CompetenceFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_class', models.CharField(max_length=50)),
                ('i_class', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'CompetenceFor',
                'verbose_name_plural': 'CompetenceFors',
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_to', models.IntegerField()),
                ('data_speed', models.IntegerField()),
                ('data_refresh_interval', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Compteurs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('rue', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('activite1', models.CharField(blank=True, max_length=50, null=True)),
                ('activite2', models.CharField(blank=True, max_length=50, null=True)),
                ('activite3', models.CharField(blank=True, max_length=50, null=True)),
                ('activite4', models.CharField(blank=True, max_length=50, null=True)),
                ('activite5', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_class', models.CharField(max_length=50)),
                ('i_class', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Expertis',
                'verbose_name_plural': 'Expertises',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skillss',
            },
        ),
        migrations.CreateModel(
            name='SloganOrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('button_titre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SloganOrange',
                'verbose_name_plural': 'SloganOranges',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_class', models.CharField(max_length=50)),
                ('i_class', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('de', models.IntegerField(default=2021)),
                ('a', models.IntegerField(default=2021)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
    ]
