# Generated by Django 3.0.2 on 2020-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='fade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
