# Generated by Django 3.0.2 on 2020-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_work_fade'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
