# Generated by Django 3.0.2 on 2020-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_work_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Liens',
                'verbose_name_plural': 'Lienss',
            },
        ),
    ]
