# Generated by Django 3.0.2 on 2020-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0005_projectlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
