# Generated by Django 3.0.2 on 2020-02-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0006_auto_20200205_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Partager',
                'verbose_name_plural': 'Partagers',
            },
        ),
    ]
