# Generated by Django 3.0.2 on 2020-02-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0007_partager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partager',
        ),
    ]
