# Generated by Django 3.0.2 on 2020-02-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0008_delete_partager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='url_partage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
