# Generated by Django 3.0.2 on 2020-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0009_projectlist_url_partage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
