# Generated by Django 3.0.2 on 2020-02-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0010_auto_20200205_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CopyRight',
                'verbose_name_plural': 'CopyRights',
            },
        ),
    ]
