# Generated by Django 3.0.2 on 2020-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0011_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello1', models.CharField(max_length=50)),
                ('qui', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('cv_url', models.CharField(max_length=50)),
                ('hello2', models.CharField(max_length=50)),
                ('portfolio_url', models.CharField(max_length=50)),
                ('titre_button_portfolio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
    ]
