# Generated by Django 3.0.2 on 2020-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0012_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='bg1',
            field=models.ImageField(default='img_bg_1.jpeg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='header',
            name='bg2',
            field=models.ImageField(default='img_bg_1.jpeg', upload_to='images/'),
        ),
    ]
